### ISSUE TITLE
 Issue: Installation/Setup Issue - Z3Config.cmake missing

### ISSUE THREAD

**Issue by nalindas9** [icaros-usc/wecook#21]
### System Information
- OS Platform and Distribution: Linux Ubuntu 16.04
- ROS Version: Kinetic
- Python version: 3.7.12

### Problem
I am trying to setup wecook according to the instructions provided here - https://wecookrobotics.github.io/md_docs_instructions.html 
However, it is not building since there are dependency issues. AIKIDO was not building for my system since I am using Ubuntu Xenial - ROS Kinetic and apparently AIKIDO is only supported for Ubuntu Trusty- ROS Indigo according to the installation instructions provided here - https://github.com/personalrobotics/aikido 

I found a workaround for installing AIKIDO on Ubuntu 16.04 - ROS Kinetic by following the instructions here - https://github.com/usc-csci-545-fall-2019/AIKIDO-Tutorial

Now I am able to build the AIKIDO packages successfully. However, now I am having trouble with the Z3 Dependency. I  have installed Z3 in the default system wide location. 

But on building wecook, it is not able to find the Z3 Installation. This is the error I am getting: 
![z3](https://user-images.githubusercontent.com/44141068/79670594-3c97a180-8192-11ea-9632-c0a676a7d1ac.png)

As a workaround, I tried setting the Z3_DIR path in the CMakeLists.txt in wecook like this:
![cmake](https://user-images.githubusercontent.com/44141068/79670642-94cea380-8192-11ea-8222-2cadf2ad8e9f.png)

But still it is not able to find the `Z3Config.cmake` file as there is no such file inside the Z3 cmake folder. It only has the `Z3Config.cmake.in` file. 

### Comments
Could you let me know how to resolve this dependency issue? How do I set the correct Z3_DIR path for wecook to find the Z3 Installation?

Thanks!

**Comment by hejia-zhang** [comment]
Hi Nalin, I wonder if you used cmake to build z3.

**Comment by nalindas9** [comment]
Hi @hejia-zhang,

Thanks for your response! I used Cmake to build Z3. Now it's able to find the Z3 build. However, wecook failed building because of libdart 6.7 (on my system) conflict with libdart 6.9 (required by wecook) which I resolved by removing libdart and reinstalling libdart through apt-get which installed libdart 6.9.
 
 However, I am getting this error now:
![Screenshot from 2020-04-21 17-04-31](https://user-images.githubusercontent.com/44141068/79914004-82eb3b80-83f2-11ea-90b9-f693cf64a706.png)

While installing the build dependencies for DART - https://github.com/usc-csci-545-fall-2019/AIKIDO-Tutorial/blob/master/README.md , it also removes my current moveit installation.

Can you let me know why I am getting this error?

**Comment by nalindas9** [comment]
Hi @hejia-zhang,

I tried following the setup instructions as suggested here: https://github.com/icaros-usc/wecook/blob/master/docs/instructions.md 

I built both Z3 and DART from source using cmake. But I am still geting the same error as above. I think it is an issue with wecook not being able to find the correct OMPL installation. I had installed OMPL using `apt-get install libompl-dev`. I even tried building OMPL using cmake.

It would be great if you could help me out with this asap.
Thanks!

**Comment by nalindas9** [comment]
Solved the issue. Was a dependency conflict of `libfcl-dev` and `libfcldev-0.5-dev`( Moveit). After reinstalling Ubuntu, it built successfully. Thanks!
